---
title: "Computer Lab 3: High Dimensional Data Analysis"
author: "Sara Kopelman"
date: today
date-format: long
format:
  pdf:
    toc: false
    number-sections: false
    booktabs: true
header-includes:
  - \usepackage{float}  
---

# Part 1: Multivariate regression analysis

## 1)

```{r}
data.df <- read.table("ami.data.txt")
names <- c("Y1","Y2","Z1","Z2","Z3","Z4","Z5")
colnames(data.df) <- names
summary(data.df)
pairs(data.df)
```

## 2)

```{r}
model.Y1 <- lm (Y1 ~ Z1 + Z2 + Z3 +Z4 + Z5, data = data.df)
summary(model.Y1)

res.Y1 <- resid(model.Y1)
plot(res.Y1)


new.df        <- data.frame(Z1 =1, Z2 = 1250, Z3 = 150, Z4 = 70, Z5 = 85)
prediction.Y1 <- predict(model.Y1, new.df,interval = "prediction", level = 0.95)
prediction.Y1
```

## 3)

```{r}
library(car)
model <- lm(cbind(Y1, Y2) ~ Z1 + Z2 + Z3 +Z4 + Z5, data = data.df)
summary(model)

Manova(model)

prediction <- predict(model, new.df)    
```

```{r}
confidenceEllipse <- function(mod, newdata, level = 0.95, ggplot = TRUE){
  # labels
  lev_lbl <- paste0(level * 100, "%")
  resps <- colnames(mod$coefficients)
  title <- paste(lev_lbl, "confidence ellipse for", resps[1], "and", resps[2])
  
  # prediction
  p <- predict(mod, newdata)
  
  # center of ellipse
  cent <- c(p[1,1],p[1,2])
  
  # shape of ellipse
  Z <- model.matrix(mod)
  Y <- mod$model[[1]]
  n <- nrow(Y)
  m <- ncol(Y)
  r <- ncol(Z) - 1
  S <- crossprod(resid(mod))/(n-r-1)
  
  # radius of circle generating the ellipse
  # see Johnson and Wichern (2007), p. 399
  tt <- terms(mod)
  Terms <- delete.response(tt)
  mf <- model.frame(Terms, newdata, na.action = na.pass,
                    xlev = mod$xlevels)
  z0 <- model.matrix(Terms, mf, contrasts.arg = mod$contrasts)
  rad <- sqrt((m*(n-r-1)/(n-r-m)) * qf(level,m,n-r-m) *
                z0 %*% solve(t(Z)%*%Z) %*% t(z0))
  
  # generate ellipse using ellipse function in car package
  ell_points <- car::ellipse(center = c(cent), shape = S,
                             radius = c(rad), draw = FALSE)
  
  # ggplot2 plot
  if(ggplot){
    ell_points_df <- as.data.frame(ell_points)
    ggplot2::ggplot(ell_points_df, ggplot2::aes(.data[["x"]], .data[["y"]])) +
      ggplot2::geom_path() +
      ggplot2::geom_point(ggplot2::aes(x = .data[[resps[1]]], 
                                       y = .data[[resps[2]]]),
                          data = data.frame(p)) +
      ggplot2::labs(x = resps[1], y = resps[2],
                    title = title)
  } else {
    # base R plot
    plot(ell_points, type = "l",
         xlab = resps[1], ylab = resps[2],
         main = title)
    points(x = cent[1], y = cent[2])
  }
}
confidenceEllipse(mod = model, newdata = new.df)

```

# Part 2: James–Stein estimator

```{r}
load("Lab3.Rdata")
dim(xx) #genes are on columns
m1 <- apply(xx,2,'mean')
xx1 <- scale(xx) 

hist(m1, main = "Histogram of Column Means", xlab = "Means", col = "lightblue")
xx1 <- scale(xx)          #Standardize the data
xx1 <- sweep(xx1,2,m1,'+')#Add the column means back to the standardized data
m1  <- apply(xx1,2,'mean')
hist(m1) 
n   <- dim(xx1)[1]
p   <- dim(xx1)[2]

# (b) ----
xx1 <- xx1-10
m1  <- apply(xx1,2,'mean')
hist(m1) 
```

```{r}
X1  <- xx1[1:5,] 
X2  <- xx1[6:n,]

mle   <- apply(X1,2,'mean') #MLE from first 5 rows
tmean <- apply(X2,2,'mean') #Test mean from remaining rows

plot(tmean ~ mle)
abline(a=0,b=1)
sum((tmean-mle)^2)


JS1 <- (1-(p-2)/sum((mle^2))/5)*mle
points(tmean ~ JS1, col='red')
sum((tmean-JS1)^2)

d   <- (p-3)/(p-1)/5/var(mle)
JS2 <-(1-d)*mle+d*mean(mle)

points(tmean~JS2, col='green')
sum((tmean-JS2)^2)

```

# Part 3: Simulation study: model selection

```{r}
rm(list = ls())
set.seed(500)

# --------------------------
# Parameters
# --------------------------
n <- 1000
p <- 950
klist <- c(2, 5, 10, 100, 500, 950)
rep1 <- 50

# --------------------------
# Allocate matrices
# --------------------------
PE    <- matrix(0, rep1, length(klist))
PRED1 <- matrix(0, rep1, length(klist))
PRED2 <- matrix(0, rep1, length(klist))
PRED3 <- matrix(0, rep1, length(klist))

# --------------------------
# True data
# --------------------------
beta <- c(rep(3, 5), rep(0, p - 5))
Z    <- matrix(rnorm(n * p, 0, 1 / sqrt(n)), nrow = n)
mu   <- Z %*% beta

# --------------------------
# Precompute matrices that do not depend on Y
# --------------------------
ZTZ_list <- vector("list", length(klist))
invZTZ  <- vector("list", length(klist))
Zt_list <- vector("list", length(klist))
hdiag   <- vector("list", length(klist))

for (i in seq_along(klist)) {
  k   <- klist[i]
  Zk  <- Z[, 1:k, drop = FALSE]
  ZtZ <- crossprod(Zk)
  inv <- solve(ZtZ)
  
  ZTZ_list[[i]] <- ZtZ        # Gram matrix
  invZTZ[[i]]   <- inv        # inverse of Gram
  Zt_list[[i]]  <- t(Zk)      # transpose
  
  # diagonal of projection matrix H = Zk %*% inv %*% t(Zk)
  hdiag[[i]] <- rowSums((Zk %*% inv) * Zk)
}

# --------------------------
# Simulation loop
# --------------------------
for (j in 1:rep1) {
  
  # Generate new noise and response
  epsilon <- rnorm(n)
  Y       <- mu + epsilon
  
  # Loop over different k
  for (i in seq_along(klist)) {
    k   <- klist[i]
    Zk  <- Z[, 1:k, drop = FALSE]
    Zt  <- Zt_list[[i]]
    inv <- invZTZ[[i]]
    
    # Compute beta_hat and mu_hat efficiently
    betahat <- solve(ZTZ_list[[i]], Zt %*% Y)
    muhat   <- Zk %*% betahat
    
    # Residual sum of squares
    RSS <- sum((Y - muhat)^2)
    
    # Compute metrics
    PE[j, i]    <- sum((muhat - mu)^2) + n
    PRED1[j, i] <- RSS + 2 * k
    PRED2[j, i] <- RSS * (1 + 2 * k / (n - k))
    
    # Leave-one-out residuals
    res1        <- (Y - muhat) / (1 - hdiag[[i]])
    PRED3[j, i] <- sum(res1^2)
  }
}

# --------------------------
# Optional: Check results
# --------------------------
PE
PRED1
PRED2
PRED3


boxplot(PE) 
boxplot(PE-PE[,2])
length(which(PE-PE[,2]<0))
boxplot(PE[,1:3]-PE[,2])
boxplot(PRED1-PRED1[,2])
length(which(PRED1-PRED1[,2]<0))

boxplot(PRED1[,1:3]-PRED1[,2])
boxplot(PRED2-PRED2[,2])
length(which(PRED2-PRED2[,2]<0))

boxplot(PRED2[,1:3]-PRED2[,2])
boxplot(PRED3-PRED3[,2])
boxplot(PRED3[,1:3]-PRED3[,2])
length(which(PRED3-PRED3[,2]<0))


boxplot(PRED1-PE)
boxplot(PRED2-PE)
boxplot(PRED2[,1:5]-PE[,1:5])
boxplot(PRED3[,1:5]-PE[,1:5])
```

```{r}
rm(list = ls())

n <- 1000
p <- 950
PE<- rep(0,6)
PRED1 <- rep(0,6)
PRED2 <- rep(0,6)
PRED3 <- rep(0,6)

Z <- matrix(rnorm(n*p,0,1/sqrt(n)),nrow=n)

beta      <-rep(0,p) 
beta[1:5] <-3

mu      <- Z %*% beta
epsilon <- rnorm(n)

Y       <- mu + epsilon

i <- 1

for (k in c(2,5,10,100,500,950))
{  
  Zn <- Z[,1:k]
  M1 <- solve(t(Zn)%*%Zn)%*%t(Zn)
  M2 <- Zn%*%M1
  betahat <- M1%*%Y
  muhat   <- Zn%*%betahat
  PE[i]   <- sum((muhat-mu)^2) + n
  RSS     <- sum((muhat-Y)^2)
  PRED1[i]<- RSS + 2*k
  PRED2[i]<- RSS*(1 + 2*k/(n-k)) 
  res1    <- (Y-muhat)/(1-diag(M2))
  PRED3[i]<- sum(res1^2)
  i = i+1
} 


###50 replicates

rep1 <- 50 


PE   <- matrix(rep(0,6*rep1),nrow=rep1)
PRED1<- matrix(rep(0,6*rep1),nrow=rep1)
PRED2<- matrix(rep(0,6*rep1),nrow=rep1)
PRED3<- matrix(rep(0,6*rep1),nrow=rep1)
beta <- rep(0,p)
beta[1:5]<-3
Z    <- matrix(rnorm(n*p,0,1/sqrt(n)),nrow=n)
mu   <- Z%*%beta


for (j in 1:rep1)
  
{
  
  epsilon <-rnorm(n)
  
  Y  <- mu+epsilon
  
  i=1
  
  for (k in c(2,5,10,100,500,950))
  {  
    Zn <- Z[,1:k];
    M1 <- solve(t(Zn)%*%Zn)%*%t(Zn)
    M2 <- Zn%*%M1
    betahat <- M1%*%Y
    muhat   <- Zn%*%betahat
    PE[j,i] <- sum((muhat-mu)^2)+n
    RSS     <- sum((muhat-Y)^2)
    PRED1[j,i]<- RSS + 2*k
    PRED2[j,i]<- RSS*(1+2*k/(n-k))
    res1      <- (Y-muhat)/(1-diag(M2))
    PRED3[j,i]<- sum(res1^2)
    i=i+1
  } 
}   

boxplot(PE) 
boxplot(PE-PE[,2])
length(which(PE-PE[,2]<0))
boxplot(PE[,1:3]-PE[,2])
boxplot(PRED1-PRED1[,2])
length(which(PRED1-PRED1[,2]<0))

boxplot(PRED1[,1:3]-PRED1[,2])
boxplot(PRED2-PRED2[,2])
length(which(PRED2-PRED2[,2]<0))

boxplot(PRED2[,1:3]-PRED2[,2])
boxplot(PRED3-PRED3[,2])
boxplot(PRED3[,1:3]-PRED3[,2])
length(which(PRED3-PRED3[,2]<0))


boxplot(PRED1-PE)
boxplot(PRED2-PE)
boxplot(PRED2[,1:5]-PE[,1:5])
boxplot(PRED3[,1:5]-PE[,1:5])
```

```{r}
n <- 1000
p <- 950
sigma <- 1 / sqrt(n)
Z <- matrix(rnorm(n * p, mean = 0, sd = sigma), nrow = n, ncol = p)

beta = rep(0,950)
beta[1:5] <- 3 #This model will not have an intercept
epsilon <- rnorm(n)

Y = Z%*%beta + epsilon

subset = c(2,5,10,100,500,950)

for 
```
