---
title: "Lab 1"
author: "Sara Kopelman"
date: today
format: html
---

## Part 0

Don't forget to add AI usage

```{r}
L <- matrix(c(4,1, 1, 3), nrow=2, byrow=TRUE)
u <- c(2,-1)
v <- c(3,1)
#i
tL <- t(L)
detL <-det(L)
rankL <- qr(L)$rank
trL <- sum(diag(L))

#ii
isLInvert <- detL != 0
Linv <- solve(L)
 
#iii
Lu <- L%*%u

#iv
eigenL <- eigen(L)
eigenValL <- eigenL$values
eigenVecL <- eigenL$vectors

#v
uTLu <- t(u) %*% Lu

#vi
vuTv <- v %*% (t(u) %*% v)
inProd <- crossprod(u,vuTv) #Check this
```

## Part 1

```{r}
data(iris)
#i
print(summary(iris))
IrisMeans <- colMeans(iris[, 1:4])
#ii
pairs(iris[, 1:4])
#iii
R <- cor(iris[, 1:4])
print(R)
#iv
par(mfrow=c(2, 2))
for(i in 1:4) {
  hist(iris[, i], main=colnames(iris)[i], xlab=colnames(iris)[i])
}
```

## Part 2

```{r}
WL <- read.table("WeightLength.txt",header = TRUE, sep = "\t")
#i
meanWL <- colMeans(WL)
S <- var(WL)
#ii
hist(WL[,1])
qqnorm(WL[,1])
qqline(WL[,1], col = "blue") 

hist(WL[,2])
qqnorm(WL[,2])
qqline(WL[,2], col = "blue") 

#iii
library('ellipse')
plot(ellipse(S,centre = meanWL, level = c(0.95,0.75), npoints=1000),pch=".",col="red" )
points(WL,col="blue")

#iv
n <- nrow(WL)
p <- ncol(WL)
(n-1)*p/(n-p)*qf(0.95,p,n)
qchisq(0.95,p)

scoring=function(Data){
  n=dim(Data)[1]
  scoring=vector("numeric",n)
  s=var(Data)
  si=solve(s)
  m=colMeans(Data)
  for( i in 1:n){
    xm=t(as.matrix(Data[i,]-m))
    scoring[i]=t(xm)%*%si%*%xm
  }
  scoring
}
Score <- scoring(WL); head(Score)

FinalScore <- rep(1,n)

te  <- (n-1)*p/(n-p)*qf(0.95,p,n)
te2 <- (n-1)*p/(n-p)*qf(0.75,p,n)

FinalScore[Score>te]=0
FinalScore[Score<=te2]=2

points(WL[FinalScore==2,],col="green")
points(WL[FinalScore==1,],col="blue")
points(WL[FinalScore==0,],col="yellow")
mean(FinalScore==0)
mean(FinalScore==1)
mean(FinalScore==2)

#v
E <- eigen(S)
u <- E$vectors
NewData <- as.matrix(WL) %*% u

#vi
plot(NewData) #check this
```

```{r}
set.seed(6)
#i
n <- c(20,50,200,2000)
mu = c(0,0)
sigma = matrix(c(1,0.5, 0.5, 1), nrow=2, byrow=TRUE)

normSim <-function(n,mu,sigma){
  R <- chol(sigma)
  Z <- matrix(rnorm(n * length(mu)), nrow = n)
  X <- Z %*% R + matrix(mu, nrow = n, ncol = length(mu), byrow = TRUE)
  return(X)
}

#ii

Sims <- lapply(n, function(n) normSim(n, mu, sigma))
names(Sims) <- paste0("n_", n)

#iii

Means <- lapply(Sims,colMeans)
Covs <- lapply(Sims,cov)
SE_Mean <- lapply(Means, function(m) sum((m-mu)^2))
SE_Cov <- lapply(Covs, function(c) sum((c - sigma)^2))

#iv/v
reps <- 500
SE_mean_reps <- matrix(NA,nrow=reps,ncol = length(n))
SE_cov_reps <- matrix(NA,nrow=reps,ncol = length(n))
Mean_vectors <- vector("list", length(n))
names(Mean_vectors) <- paste0("n_", n)
for (j in 1:length(n)) {
  Mean_vectors[[j]] <- matrix(NA, nrow = reps, ncol = length(mu))
}

for (i in 1:reps) {
  sims <-lapply(n, function(n) normSim(n, mu, sigma))
  means <-lapply(sims,colMeans)
  covs <- lapply(sims,cov)
  SE_mean <- sapply(means, function(m) sum((m - mu)^2))
  SE_cov  <- sapply(covs, function(c) sum((c - sigma)^2))
  
  SE_mean_reps[i, ] <- SE_mean
  SE_cov_reps[i, ] <- SE_cov
  
  for (j in 1:length(n)) {
    Mean_vectors[[j]][i, ] <- means[[j]]
  }
}

MSE_mean <- colMeans(SE_mean_reps)
MSE_cov <- colMeans(SE_cov_reps)
#vi
colors <- c("red","blue","green","orange")
plot(Mean_vectors[[1]], xlim = range(sapply(Mean_vectors, range)),
     ylim = range(sapply(Mean_vectors, range)), col = colors[1],
     xlab = "Mean X1", ylab = "Mean X2", pch = 16)
for (j in 2:length(n)) {
  points(Mean_vectors[[j]], col = colors[j], pch = 16)
}
legend("topright", legend = paste0("n=", n), col = colors, pch = 16)

#vii
Cov_Mean_empirical <- lapply(Mean_vectors, cov)
Cov_Mean_theoretical <- lapply(n, function(nn) sigma / nn)
```
